**Prof: [Hugo Bowne Anderson](https://www.datacamp.com/instructors/hugobowne)**

---

# Python Basics
Python fue concebido por Guido Van Rossum

### **Variables and Types**

In [9]:
# Convertir de numerico a string
var_num = 10
print(type(var_num))
var_num = str(var_num)
print(f">> {type(var_num)}")

<class 'int'>
>> <class 'str'>


In [10]:
# Convertir de string a numerico
var_num = "18.2"
print(type(var_num))
var_num = float(var_num)
print(f">> {type(var_num)}")

<class 'str'>
>> <class 'float'>


# Python Lists

### **Python Lists**

In [11]:
list_example = [ "a", 12, True]
print(list_example)
print(type(list_example))

['a', 12, True]
<class 'list'>


In [12]:
# Lista de Listas
list_house = [["hallway", 100],
         ["kitchen", 85]]
print(list_house)
print(type(list_house))

[['hallway', 100], ['kitchen', 85]]
<class 'list'>


### **Subsetting Lists**

In [13]:
list_fam = ["heydy", 22, "ines", 54, "henry", 33,"oscar", 38]
print(list_fam)

['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 38]


In [17]:
# Indexacion
print(list_fam[2])

# Indice Negativo
print(list_fam[-6])

ines
ines


In [23]:
# Rebanado [ start : end ]
#         Inclusive : exclusive

print(list_fam[3:5]) #no toma el ultimo digito 
print(list_fam[:5]) #Desde el inicio hasta la posicion 4
print(list_fam[5:]) #Desde la posicion 5 hasta el final

[54, 'henry']
['heydy', 22, 'ines', 54, 'henry']
[33, 'oscar', 38]


### **Manipulating Lists**

In [24]:
print(list_fam)

['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 38]


In [27]:
list_fam[-1]=37
print(list_fam)

list_fam[:2]= ["Mayumy", 24]
print(list_fam)

['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 37]
['Mayumy', 24, 'ines', 54, 'henry', 33, 'oscar', 37]


In [28]:
# Adding and removing elements

# Add
fam_Ext = list_fam + ["Achuchena", 12]
print(fam_Ext)

# Delete
del(fam_Ext[3])
print(fam_Ext)

['Mayumy', 24, 'ines', 54, 'henry', 33, 'oscar', 37, 'Achuchena', 12]
['Mayumy', 24, 'ines', 'henry', 33, 'oscar', 37, 'Achuchena', 12]


In [29]:
# Interesting !!
x = ["a", "b", "c"]
y = x # Con = copias la referencia a la lista mas no los valores
y[1]="heydy"
print(x)
print(y)

['a', 'heydy', 'c']
['a', 'heydy', 'c']


In [31]:
# Creando una nueva lista Correctamente (*)
x = ["a", "b", "c"]
# y = list(x)
y = x[:]

y[1]="heydy"
print(x)
print(y)

['a', 'b', 'c']
['a', 'heydy', 'c']


In [40]:
# Example - Eliminar "poolhouse" y 24.5
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
print(areas)
# print(areas[-4:-2])
del(areas[-4:-2])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


# Functions and Packages

### **Funcion**

Es una pieza de codigo reutilizable, destinada a resolver una tarea en particular

In [10]:
list_fam = [ 22, 54, 33, 38, 36]
print(list_fam)
print(f"el tamaño de la lista {len(list_fam)}")
print(f"valor maximo de la lista {max(list_fam)}")

[22, 54, 33, 38, 36]
el tamaño de la lista 5
valor maximo de la lista 54


In [1]:
round(1.689,2)

1.69

In [5]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [4]:
first = [51.25, 18.0, 20.0]
full_sorted = sorted(first) # Ascendente
full_sorted_asc = sorted(first,reverse=False) # Ascendente
full_sorted_desc = sorted(first,reverse=True) # Descendiente
print(full_sorted)
print(full_sorted_asc)
print(full_sorted_desc)

[18.0, 20.0, 51.25]
[18.0, 20.0, 51.25]
[51.25, 20.0, 18.0]


### **Methods**

En python todo es objecto. Y cada objecto tiene metodos especificos asociados
- Objetos con diferentes tipos pueden tener metodos con el mismo nombre

In [5]:
list_fam = [ "heydy", 22, "ines", 54, "henry", 33,"oscar", 54]

print("Indice:", list_fam.index("henry")) # OBTENER el INDICE de la lista
print(f"Contar: {list_fam.count(54)}") # CONTAR cuantas veces aparece algo

Indice: 4
Contar: 2


In [9]:
name= "mayumy"
print(name.capitalize())
print(name.replace("y","*"))

Mayumy
ma*um*


In [24]:
name.upper()

'MAYUMY'

In [21]:
name.index("y")

2

In [10]:
print(list_fam)
list_fam.append("Achuchena")
print(list_fam)

['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 54]
['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 54, 'Achuchena']


In [11]:
print(list_fam)
list_fam.remove("Achuchena")
print(list_fam)

['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 54, 'Achuchena']
['heydy', 22, 'ines', 54, 'henry', 33, 'oscar', 54]


In [12]:
list_fam.reverse()
print(list_fam)

[54, 'oscar', 33, 'henry', 54, 'ines', 22, 'heydy']


**Packages**

- Un directorio de scripts de python
- Cada script es llamado "modulo"
- Estos modulos especifican funciones, metodos y nuevos tipos de python destinados a resolver problemas particulares

_**Paquetes para ciencia de datos:**_

- **_Numpy_** (para trabajar eficientemente con matrices)
- **_Matplotlib_** (para visualizacion de datos)
- **_Scikit-learn_** (para aprendizaje automatico)

> Pip - Gestor de paquetes de python

<img src="https://i.ibb.co/FBqZrfP/Selecci-n-048.png" alt="Selecci-n-048" border="0">

In [27]:
# Importancion de todo el paquete y renombrandolo
import numpy as np

In [28]:
np.array([1,2,3])

array([1, 2, 3])

In [30]:
#Importar funcion especifica de un paquete
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [42]:
r = 192500

# from math import pi
from math import radians
dist = r*radians(12)
print(dist)

40317.10572106901


In [44]:
# Suponga que quiere usar la función inv (), 
# que está en el subpaquete linalg del paquete scipy.
from scipy.linalg import inv as my_inv
my_inv([[1,2], [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# NumPy

- Numeric Python
- Es un paquete de python que ofrece una alternativa a la lista normal
- Se puede realizar calculos sobre matrices enteras
- Al ser todos sus elementos de un mismo tipo acelera sus calculos

**_Instalacion_**
```
pip3 install numpy
```

**_Importacion_**
```
import numpy as np
```

---

Numpy asume que solo contiene valores de un solo tipo. Por ejm: Matriz de booleanos, matriz de float, etc

**Numpy Arrays list**

Matrices unidimensionales

In [14]:
import numpy as np

In [47]:
height = [1.73, 1.68, 1.71, 1.89, 1.79] # lista
np_height = np.array(height) # Convirtiendo la lista en una matriz

weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_weight = np.array(weight)

print(np_height)
print(np_weight)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [53]:
print(type(np_weight))

<class 'numpy.ndarray'>


In [48]:
bmi = np_weight / np_height**2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [50]:
bmi[1]

20.97505668934241

In [51]:
bmi > 23

array([False, False, False,  True, False])

In [52]:
# Hacer subconjuntos
bmi[bmi > 23]

array([24.7473475])

**2D Numpy Arrays**

Matrices bidimensionales

In [54]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [56]:
np_2d.shape # 2fila y 5columnas

(2, 5)

In [57]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [58]:
print(np_2d[0][2])
print(np_2d[0,2])

1.71
1.71


In [60]:
print(np_2d[:,1:3])

[[ 1.68  1.71]
 [59.2  63.6 ]]


**Numpy: Basic Statistics**

Generar estadisticas resumidas sobre sus datos

In [18]:
# Creando MUESTRAS ALEATORIAS con DISTRIBUCION NORMAL
# np.random.normal(loc:Media, scale:Standard desviation ,size:# muestras)

height = np.round(np.random.normal(1.75, 0.20, 5000),2) # ALTURA
Weight = np.round(np.random.normal(60.32, 15, 5000),2) # PESO

np_city = np.column_stack((height,Weight)) # stack -- pegar como 2 columnas

print(np_city)
print(np.mean(np_city[:,0])) # Promedio - Average

[[ 1.81 49.21]
 [ 1.91 55.59]
 [ 1.88 55.91]
 ...
 [ 1.74 37.59]
 [ 1.67 86.67]
 [ 1.93 40.64]]
1.7489620000000003


In [72]:
np.median(np_city[:,0]) # Mediana

1.75

In [73]:
# Hallar la correlacion 
# Para visualizar si 2 variables tiene alguna relacion lineal
np.corrcoef(np_city[:,0], np_city[:,1]) 

array([[ 1.        , -0.00436472],
       [-0.00436472,  1.        ]])

In [74]:
# Desviacion estandar
# Mide la distancia entre cada dato respecto a su promedio
# Mayor desviacion estandar -> mayor dispersion
np.std(np_city[:,0])

0.19983133283847154